---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockzrs-frontend
  namespace: stockzrs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockzrs-frontend
  template:
    metadata:
      labels:
        app: stockzrs-frontend
    spec:
      containers:
      - name: stockzrs-frontend
        env:
        - name: STOCKZRS_RELAY_SERVICE_WS_URL
          value: "wss://stockzrs-relay-service.stockzrs.com"
        image: PLACEHOLDER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: stockzrs-frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: stockzrs-frontend
  namespace: stockzrs-frontend
spec:
  selector:
    app: stockzrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-websocket
  namespace: stockzrs-frontend
spec:
  podSelector:
    matchLabels:
      app: stockzrs-frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
