---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockzrs-frontend
  namespace: stockzrs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockzrs-frontend
  template:
    metadata:
      labels:
        app: stockzrs-frontend
    spec:
      containers:
      - name: stockzrs-frontend
        image: PLACEHOLDER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stockzrs-frontend
  namespace: stockzrs-frontend
spec:
  selector:
    app: stockzrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80